"""Initial tables for CDS data

Revision ID: 2cf317c905fa
Revises: 
Create Date: 2025-11-16 02:10:04.938362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf317c905fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cds_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_date_desc', 'cds_records', [sa.text('date DESC')], unique=False)
    op.create_index('idx_date_range', 'cds_records', ['date'], unique=False)
    op.create_index(op.f('ix_cds_records_date'), 'cds_records', ['date'], unique=True)
    op.create_index(op.f('ix_cds_records_id'), 'cds_records', ['id'], unique=False)
    op.create_table('data_update_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_update_logs_id'), 'data_update_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_update_logs_id'), table_name='data_update_logs')
    op.drop_table('data_update_logs')
    op.drop_index(op.f('ix_cds_records_id'), table_name='cds_records')
    op.drop_index(op.f('ix_cds_records_date'), table_name='cds_records')
    op.drop_index('idx_date_range', table_name='cds_records')
    op.drop_index('idx_date_desc', table_name='cds_records')
    op.drop_table('cds_records')
    # ### end Alembic commands ###
